Add solution for UnitTests
unbrokable/Denis_Zhuravel_HomeWork pull request #11
Opened 2021-05-31 14:33 UTC by unbrokable

2021-06-03 14:33 UTC, vladimir-shirmanov requested changes
читай комменты. Надо бы сделать рефакторинг самого калькулятора, а то пока он выглядит довольно грязно и не оптимально

2021-06-03 14:33 UTC, vladimir-shirmanov commented on Calculator_TDD/Calculator_TDD/Calculator.cs
> +            if (arrNegativeNumbers.Count() == 1)
не внимательно прочел задание. Надо было это одно отрицательное число тоже выводить

2021-06-03 14:33 UTC, vladimir-shirmanov commented on Calculator_TDD/Calculator_TDD/Calculator.cs
> +        public event Action<string, int> AddOccured;
А в чем смысл этот события? и к тому же как проверить тогда что оно действительно возникло в тестах, если оно ничего не делает

2021-06-03 14:33 UTC, vladimir-shirmanov commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "negatives not allowed");
тут перепутал места экспектед и актуал

2021-06-03 14:33 UTC, vladimir-shirmanov commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "negatives not allowed -11,-12");
и тут

2021-06-03 14:33 UTC, vladimir-shirmanov commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "Event is work");
и тут

2021-06-06 17:41 UTC, unbrokable commented on Calculator_TDD/Calculator_TDD/Calculator.cs
> +            if (arrNegativeNumbers.Count() == 1)
Исправил

2021-06-06 17:44 UTC, unbrokable commented on Calculator_TDD/Calculator_TDD/Calculator.cs
> +        public event Action<string, int> AddOccured;
Это события для 8 задания 
Проверку в тестах я делаю с помощью вызова исключения с текстом что функция вызвалась

2021-06-06 17:45 UTC, unbrokable commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "negatives not allowed");
Исправил

2021-06-06 17:45 UTC, unbrokable commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "negatives not allowed -11,-12");
Исправил

2021-06-06 17:45 UTC, unbrokable commented on Calculator_TDD/TestCalculator/CalculatorTest.cs
> +            Assert.AreEqual(exception.Message, "Event is work");
Исправил

2021-07-10 18:40 UTC, merged