Add html pages
unbrokable/Denis_Zhuravel_HomeWork pull request #14
Opened 2021-06-18 16:30 UTC by unbrokable

2021-06-22 10:01 UTC, romanPatsev commented on Practise/index4.html
> +    <a href="index2.html">ссылка на вторую страницу</a>
добавь еще курсивы `<i>`

2021-06-22 10:03 UTC, romanPatsev commented on Practise/index7.html
> +<body>
толщина границ больше + выравнивание ячейки 1 слева

2021-06-22 10:05 UTC, romanPatsev commented on Practise/Css/style.css
> +    font-size: 24;
нет единиц, нужно выделить жирным

2021-06-22 10:16 UTC, romanPatsev requested changes

2021-06-22 10:16 UTC, romanPatsev commented on Practise/index11.html
> +<!DOCTYPE html>
Не совпадает с оригиналом

2021-06-22 10:16 UTC, romanPatsev commented on Practise/Css/style.css
> +    background-color: lime;
зачем такой едкий цвет ?)

2021-06-22 10:16 UTC, romanPatsev commented on Practise/index12.html
> +    <div class="list-menu">
менюшки нужно делать с помощью `<ul><li>` внутрь ли заворачивать `<a href="#">`

2021-06-27 11:49 UTC, unbrokable commented on Practise/index4.html
> +    <a href="index2.html">ссылка на вторую страницу</a>
Исправил 
Добавил

2021-06-27 11:49 UTC, unbrokable commented on Practise/index7.html
> +<body>
Исправил

2021-06-27 11:49 UTC, unbrokable commented on Practise/Css/style.css
> +    font-size: 24;
Исправил

2021-06-27 11:49 UTC, unbrokable commented on Practise/index11.html
> +<!DOCTYPE html>
Исправил

2021-06-27 11:50 UTC, unbrokable commented on Practise/Css/style.css
> +    background-color: lime;
Исправил 
Сделал обычный зеленый

2021-06-27 11:50 UTC, unbrokable commented on Practise/index12.html
> +    <div class="list-menu">
Исправил

2021-06-29 08:52 UTC, romanPatsev commented
Ок, можешь мерджить

2021-06-29 10:39 UTC, merged